// AUTO-GENERATED by ../_harness.ts on server start — do not edit by hand.
// The zod-free runtime manifest. Imported by client.ts as a plain data module, which is
// why the bundler can tree-shake zod out of the browser build (no plugin required).
/* eslint-disable */
import type { Manifest } from '@ayepi/core/client';

const manifest: Manifest = {
  "endpoints": {
    "login": {
      "method": "POST",
      "path": "/login",
      "ws": null,
      "httpOnly": false,
      "streamIn": null,
      "itemsIn": false,
      "streamOut": null,
      "items": false,
      "p": [],
      "q": [],
      "b": [
        "user"
      ],
      "f": [],
      "hasBody": true,
      "hasHeaders": false,
      "multi": false,
      "bodyEnc": "json"
    },
    "addNote": {
      "method": "POST",
      "path": "/addNote",
      "ws": null,
      "httpOnly": false,
      "streamIn": null,
      "itemsIn": false,
      "streamOut": null,
      "items": false,
      "p": [],
      "q": [],
      "b": [
        "token",
        "text"
      ],
      "f": [],
      "hasBody": true,
      "hasHeaders": false,
      "multi": false,
      "bodyEnc": "json"
    },
    "listNotes": {
      "method": "GET",
      "path": "/listNotes",
      "ws": null,
      "httpOnly": false,
      "streamIn": null,
      "itemsIn": false,
      "streamOut": null,
      "items": false,
      "p": [],
      "q": [],
      "b": null,
      "f": [],
      "hasBody": false,
      "hasHeaders": false,
      "multi": false,
      "bodyEnc": null
    },
    "stats": {
      "method": "GET",
      "path": "/stats",
      "ws": null,
      "httpOnly": false,
      "streamIn": null,
      "itemsIn": false,
      "streamOut": null,
      "items": false,
      "p": [],
      "q": [],
      "b": null,
      "f": [],
      "hasBody": false,
      "hasHeaders": false,
      "multi": false,
      "bodyEnc": null
    }
  },
  "events": {
    "noteAdded": {
      "ws": "noteAdded",
      "hasParams": false
    }
  }
};

/** Manifests for apps that talk to more than one spec, keyed by name. */
export const manifests: Record<string, Manifest> = {};

export default manifest;
