// AUTO-GENERATED by ../_harness.ts on server start — do not edit by hand.
// The zod-free runtime manifest. Imported by client.ts as a plain data module, which is
// why the bundler can tree-shake zod out of the browser build (no plugin required).
/* eslint-disable */
import type { Manifest } from '@ayepi/core/client';

const manifest: Manifest = {
  "endpoints": {
    "presignUpload": {
      "method": "POST",
      "path": "/presignUpload",
      "ws": null,
      "httpOnly": false,
      "streamIn": null,
      "itemsIn": false,
      "streamOut": null,
      "items": false,
      "p": [],
      "q": [],
      "b": [
        "key",
        "contentType"
      ],
      "f": [],
      "hasBody": true,
      "hasHeaders": false,
      "multi": false,
      "bodyEnc": "json"
    },
    "presignDownload": {
      "method": "POST",
      "path": "/presignDownload",
      "ws": null,
      "httpOnly": false,
      "streamIn": null,
      "itemsIn": false,
      "streamOut": null,
      "items": false,
      "p": [],
      "q": [],
      "b": [
        "key"
      ],
      "f": [],
      "hasBody": true,
      "hasHeaders": false,
      "multi": false,
      "bodyEnc": "json"
    },
    "listFiles": {
      "method": "GET",
      "path": "/listFiles",
      "ws": null,
      "httpOnly": false,
      "streamIn": null,
      "itemsIn": false,
      "streamOut": null,
      "items": false,
      "p": [],
      "q": [],
      "b": null,
      "f": [],
      "hasBody": false,
      "hasHeaders": false,
      "multi": false,
      "bodyEnc": null
    },
    "removeFile": {
      "method": "POST",
      "path": "/removeFile",
      "ws": null,
      "httpOnly": false,
      "streamIn": null,
      "itemsIn": false,
      "streamOut": null,
      "items": false,
      "p": [],
      "q": [],
      "b": [
        "key"
      ],
      "f": [],
      "hasBody": true,
      "hasHeaders": false,
      "multi": false,
      "bodyEnc": "json"
    },
    "ayepiFilesDownload": {
      "method": "GET",
      "path": "/_files",
      "ws": null,
      "httpOnly": true,
      "streamIn": null,
      "itemsIn": false,
      "streamOut": "application/octet-stream",
      "items": false,
      "p": [],
      "q": [
        "t"
      ],
      "b": null,
      "f": [],
      "hasBody": false,
      "hasHeaders": false,
      "multi": false,
      "bodyEnc": null
    },
    "ayepiFilesUpload": {
      "method": "PUT",
      "path": "/_files",
      "ws": null,
      "httpOnly": true,
      "streamIn": "application/octet-stream",
      "itemsIn": false,
      "streamOut": null,
      "items": false,
      "p": [],
      "q": [
        "t"
      ],
      "b": null,
      "f": [],
      "hasBody": false,
      "hasHeaders": false,
      "multi": false,
      "bodyEnc": null
    }
  },
  "events": {}
};

/** Manifests for apps that talk to more than one spec, keyed by name. */
export const manifests: Record<string, Manifest> = {};

export default manifest;
