// AUTO-GENERATED by ../_harness.ts on server start — do not edit by hand.
// The zod-free runtime manifest. Imported by client.ts as a plain data module, which is
// why the bundler can tree-shake zod out of the browser build (no plugin required).
/* eslint-disable */
import type { Manifest } from '@ayepi/core/client';

const manifest: Manifest = {
  "endpoints": {
    "login": {
      "method": "POST",
      "path": "/login",
      "ws": null,
      "httpOnly": false,
      "streamIn": null,
      "itemsIn": false,
      "streamOut": null,
      "items": false,
      "p": [],
      "q": [],
      "b": [
        "user"
      ],
      "f": [],
      "hasBody": true,
      "hasHeaders": false,
      "multi": false,
      "bodyEnc": "json"
    },
    "ping": {
      "method": "GET",
      "path": "/ping",
      "ws": null,
      "httpOnly": false,
      "streamIn": null,
      "itemsIn": false,
      "streamOut": null,
      "items": false,
      "p": [],
      "q": [],
      "b": null,
      "f": [],
      "hasBody": false,
      "hasHeaders": false,
      "multi": false,
      "bodyEnc": null
    },
    "me": {
      "method": "GET",
      "path": "/me",
      "ws": null,
      "httpOnly": false,
      "streamIn": null,
      "itemsIn": false,
      "streamOut": null,
      "items": false,
      "p": [],
      "q": [],
      "b": null,
      "f": [],
      "hasBody": false,
      "hasHeaders": false,
      "multi": false,
      "bodyEnc": null
    },
    "enqueue": {
      "method": "POST",
      "path": "/enqueue",
      "ws": null,
      "httpOnly": false,
      "streamIn": null,
      "itemsIn": false,
      "streamOut": null,
      "items": false,
      "p": [],
      "q": [],
      "b": [
        "n"
      ],
      "f": [],
      "hasBody": true,
      "hasHeaders": false,
      "multi": false,
      "bodyEnc": "json"
    },
    "listJobs": {
      "method": "GET",
      "path": "/listJobs",
      "ws": null,
      "httpOnly": false,
      "streamIn": null,
      "itemsIn": false,
      "streamOut": null,
      "items": false,
      "p": [],
      "q": [],
      "b": null,
      "f": [],
      "hasBody": false,
      "hasHeaders": false,
      "multi": false,
      "bodyEnc": null
    },
    "snapshot": {
      "method": "GET",
      "path": "/snapshot",
      "ws": null,
      "httpOnly": false,
      "streamIn": null,
      "itemsIn": false,
      "streamOut": null,
      "items": false,
      "p": [],
      "q": [],
      "b": null,
      "f": [],
      "hasBody": false,
      "hasHeaders": false,
      "multi": false,
      "bodyEnc": null
    },
    "tools": {
      "method": "GET",
      "path": "/tools",
      "ws": null,
      "httpOnly": false,
      "streamIn": null,
      "itemsIn": false,
      "streamOut": null,
      "items": false,
      "p": [],
      "q": [],
      "b": null,
      "f": [],
      "hasBody": false,
      "hasHeaders": false,
      "multi": false,
      "bodyEnc": null
    }
  },
  "events": {
    "jobProgress": {
      "ws": "jobProgress",
      "hasParams": true
    }
  }
};

/** Manifests for apps that talk to more than one spec, keyed by name. */
export const manifests: Record<string, Manifest> = {};

export default manifest;
