/**
 * # Example harness
 *
 * Shared plumbing so each example app stays exactly **three files** (shared spec,
 * server, single-file Vue client). It:
 *
 * 1. writes the spec's **zod-free manifest** to a plain `manifest.gen.ts` next to the
 *    client (regenerated on startup). The client imports it with an ordinary relative
 *    import, so a normal bundler **tree-shakes zod away** — the spec is imported
 *    type-only and the manifest module is just data, with no special build step,
 * 2. wraps the ayepi {@link Server} so `GET /` serves a tiny HTML shell and `GET /app.js`
 *    serves the client **bundled on demand with esbuild** (Vue + `@ayepi/core/client`),
 * 3. starts it on Node via `@ayepi/node`'s `serve`,
 * 4. prints the app URL + every generated-docs URL.
 *
 * This file is infrastructure, not part of any example's "3 files".
 *
 * @module
 */

import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { serve } from '@ayepi/node';
import * as esbuild from 'esbuild';
import type { AnySpec, Server } from '@ayepi/core';

/** Options for {@link runExample}. */
export interface ExampleOptions {
  /** The primary ayepi server (from `server(api, [handlers], { docs: true, … })`). It is the one served on Node, and its manifest is the `manifest.gen.ts` default export. */
  readonly app: Server<AnySpec>;
  /**
   * Extra servers whose **manifests** should also be written to `manifest.gen.ts`, keyed
   * by name — for apps composed of more than one spec. Each is exposed as
   * `import { manifests } from './manifest.gen'` (`manifests[name]`). The primary `app`
   * is always the default export.
   */
  readonly manifests?: Record<string, Server<AnySpec>>;
  /** Absolute path to the app's `client.ts` (pass `new URL('./client.ts', import.meta.url)`). */
  readonly clientEntry: string | URL;
  /** Page `<title>` and console banner. */
  readonly title: string;
  /** TCP port (default 3000). */
  readonly port?: number;
  /** WebSocket upgrade path (default `/ws`). */
  readonly wsPath?: string;
}

const shell = (title: string): string => `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${title}</title>
    <style>
      :root { color-scheme: light dark; }
      body { font: 15px/1.5 system-ui, sans-serif; max-width: 52rem; margin: 2rem auto; padding: 0 1rem; }
      h1 { margin-bottom: 0.25rem; }
      input, button, textarea, select { font: inherit; padding: 0.35rem 0.5rem; }
      button { cursor: pointer; }
      .row { display: flex; gap: 0.5rem; flex-wrap: wrap; align-items: center; margin: 0.5rem 0; }
      .card { border: 1px solid color-mix(in srgb, currentColor 20%, transparent); border-radius: 8px; padding: 0.75rem 1rem; margin: 0.5rem 0; }
      .muted { opacity: 0.7; } .err { color: #c0392b; }
      pre, code { font-family: ui-monospace, monospace; }
      pre { background: color-mix(in srgb, currentColor 8%, transparent); padding: 0.5rem 0.75rem; border-radius: 6px; overflow: auto; }
      nav a { margin-right: 1rem; }
    </style>
  </head>
  <body>
    <div id="app">loading…</div>
    <script type="module" src="/app.js"></script>
  </body>
</html>`;

/**
 * Write the spec's zod-free manifest(s) to `manifest.gen.ts` next to the client. This is
 * a plain data module — the only thing it imports is the `Manifest` *type* (erased) — so
 * `import manifest from './manifest.gen'` pulls in no zod, and the bundler is free to
 * tree-shake the (type-only) spec import away entirely.
 */
function writeManifest(appDir: string, opts: ExampleOptions): void {
  const named = Object.fromEntries(Object.entries(opts.manifests ?? {}).map(([k, a]) => [k, a.manifest()]));
  const body = `// AUTO-GENERATED by ../_harness.ts on server start — do not edit by hand.
// The zod-free runtime manifest. Imported by client.ts as a plain data module, which is
// why the bundler can tree-shake zod out of the browser build (no plugin required).
/* eslint-disable */
import type { Manifest } from '@ayepi/core/client';

const manifest: Manifest = ${JSON.stringify(opts.app.manifest(), null, 2)};

/** Manifests for apps that talk to more than one spec, keyed by name. */
export const manifests: Record<string, Manifest> = ${JSON.stringify(named, null, 2)};

export default manifest;
`;
  writeFileSync(join(appDir, 'manifest.gen.ts'), body);
}

/**
 * Bundle the client entry for the browser. Vue ships its template compiler; the shared
 * spec is type-only (erased); and `./manifest.gen` is a plain data module — so the bundle
 * carries the routing manifest but no zod (tree-shaken via the plain data import).
 */
async function bundleClient(entry: string): Promise<string> {
  const res = await esbuild.build({
    entryPoints: [entry],
    bundle: true,
    format: 'esm',
    platform: 'browser',
    target: 'es2022',
    write: false,
    sourcemap: 'inline',
    logLevel: 'silent',
    treeShaking: true,
    alias: { vue: 'vue/dist/vue.esm-bundler.js' }, // the build that ships the template compiler
    define: {
      __VUE_OPTIONS_API__: 'false',
      __VUE_PROD_DEVTOOLS__: 'false',
      __VUE_PROD_HYDRATION_MISMATCH_DETAILS__: 'false',
    },
  });
  return res.outputFiles[0]!.text;
}

/** Serve an example app (ayepi + a bundled Vue client + generated docs) on Node. */
export function runExample(opts: ExampleOptions): void {
  const port = opts.port ?? 3000;
  const wsPath = opts.wsPath ?? '/ws';
  const entry = typeof opts.clientEntry === 'string' ? opts.clientEntry : fileURLToPath(opts.clientEntry);
  const html = shell(opts.title);

  // Emit the zod-free manifest the client imports at build time (tree-shakes zod away).
  writeManifest(dirname(entry), opts);

  const wrapped: typeof opts.app = {
    ...opts.app,
    fetch: async (req: Request): Promise<Response> => {
      const { pathname } = new URL(req.url);
      if (req.method === 'GET' && (pathname === '/' || pathname === '/index.html')) {
        return new Response(html, { headers: { 'content-type': 'text/html; charset=utf-8' } });
      }
      if (req.method === 'GET' && pathname === '/app.js') {
        try {
          const js = await bundleClient(entry);
          return new Response(js, { headers: { 'content-type': 'text/javascript; charset=utf-8', 'cache-control': 'no-store' } });
        } catch (err) {
          // surface build errors in the page instead of a blank screen
          const msg = JSON.stringify(err instanceof Error ? err.message : String(err));
          return new Response(`document.getElementById('app').innerHTML = '<pre class=err>build error:\\n' + ${msg} + '</pre>';`, {
            headers: { 'content-type': 'text/javascript; charset=utf-8' },
          });
        }
      }
      return opts.app.fetch(req);
    },
  };

  serve(wrapped, {
    port,
    path: wsPath,
    onListen: ({ port }) => {
      const base = `http://localhost:${port}`;
      console.log(`\n  ${opts.title}`);
      console.log('  ' + '─'.repeat(44));
      console.log(`  App         ${base}/`);
      console.log(`  Swagger UI  ${base}/docs/swagger`);
      console.log(`  ReDoc       ${base}/docs/redoc`);
      console.log(`  AsyncAPI    ${base}/docs/asyncapi`);
      console.log(`  OpenAPI     ${base}/docs/openapi.json`);
      console.log(`  AsyncAPI    ${base}/docs/asyncapi.json`);
      console.log('  (Ctrl-C to stop)\n');
    },
  });
}
