// AUTO-GENERATED by ../_harness.ts on server start — do not edit by hand.
// The zod-free runtime manifest. Imported by client.ts as a plain data module, which is
// why the bundler can tree-shake zod out of the browser build (no plugin required).
/* eslint-disable */
import type { Manifest } from '@ayepi/core/client';

const manifest: Manifest = {
  "endpoints": {
    "history": {
      "method": "GET",
      "path": "/history",
      "ws": null,
      "httpOnly": false,
      "streamIn": null,
      "itemsIn": false,
      "streamOut": null,
      "items": false,
      "p": [],
      "q": [
        "room"
      ],
      "b": null,
      "f": [],
      "hasBody": false,
      "hasHeaders": false,
      "multi": false,
      "bodyEnc": null
    },
    "send": {
      "method": "POST",
      "path": "/send",
      "ws": null,
      "httpOnly": false,
      "streamIn": null,
      "itemsIn": false,
      "streamOut": null,
      "items": false,
      "p": [],
      "q": [],
      "b": [
        "room",
        "from",
        "text"
      ],
      "f": [],
      "hasBody": true,
      "hasHeaders": false,
      "multi": false,
      "bodyEnc": "json"
    }
  },
  "events": {
    "roomMessage": {
      "ws": "roomMessage",
      "hasParams": true
    }
  }
};

/** Manifests for apps that talk to more than one spec, keyed by name. */
export const manifests: Record<string, Manifest> = {};

export default manifest;
