// AUTO-GENERATED by ../_harness.ts on server start — do not edit by hand.
// The zod-free runtime manifest. Imported by client.ts as a plain data module, which is
// why the bundler can tree-shake zod out of the browser build (no plugin required).
/* eslint-disable */
import type { Manifest } from '@ayepi/core/client';

const manifest: Manifest = {
  "endpoints": {
    "login": {
      "method": "POST",
      "path": "/login",
      "ws": null,
      "httpOnly": false,
      "streamIn": null,
      "itemsIn": false,
      "streamOut": null,
      "items": false,
      "p": [],
      "q": [],
      "b": [
        "user"
      ],
      "f": [],
      "hasBody": true,
      "hasHeaders": false,
      "multi": false,
      "bodyEnc": "json"
    },
    "me": {
      "method": "GET",
      "path": "/me",
      "ws": null,
      "httpOnly": false,
      "streamIn": null,
      "itemsIn": false,
      "streamOut": null,
      "items": false,
      "p": [],
      "q": [],
      "b": null,
      "f": [],
      "hasBody": false,
      "hasHeaders": false,
      "multi": false,
      "bodyEnc": null
    },
    "createJob": {
      "method": "POST",
      "path": "/createJob",
      "ws": null,
      "httpOnly": false,
      "streamIn": null,
      "itemsIn": false,
      "streamOut": null,
      "items": false,
      "p": [],
      "q": [],
      "b": [
        "title"
      ],
      "f": [],
      "hasBody": true,
      "hasHeaders": false,
      "multi": false,
      "bodyEnc": "json"
    },
    "listJobs": {
      "method": "GET",
      "path": "/listJobs",
      "ws": null,
      "httpOnly": false,
      "streamIn": null,
      "itemsIn": false,
      "streamOut": null,
      "items": false,
      "p": [],
      "q": [],
      "b": null,
      "f": [],
      "hasBody": false,
      "hasHeaders": false,
      "multi": false,
      "bodyEnc": null
    },
    "uploadAttachment": {
      "method": "POST",
      "path": "/uploadAttachment",
      "ws": null,
      "httpOnly": true,
      "streamIn": null,
      "itemsIn": false,
      "streamOut": null,
      "items": false,
      "p": [],
      "q": [],
      "b": [
        "jobId"
      ],
      "f": [
        "file"
      ],
      "hasBody": true,
      "hasHeaders": false,
      "multi": false,
      "bodyEnc": "json"
    },
    "jobStatus": {
      "method": "GET",
      "path": "/jobs/:jobId/status",
      "ws": null,
      "httpOnly": false,
      "streamIn": null,
      "itemsIn": false,
      "streamOut": null,
      "items": false,
      "p": [
        "jobId"
      ],
      "q": [],
      "b": null,
      "f": [],
      "hasBody": false,
      "hasHeaders": false,
      "multi": false,
      "bodyEnc": null
    },
    "streamLog": {
      "method": "GET",
      "path": "/jobs/:jobId/log",
      "ws": null,
      "httpOnly": false,
      "streamIn": null,
      "itemsIn": false,
      "streamOut": "application/x-ndjson",
      "items": true,
      "p": [
        "jobId"
      ],
      "q": [],
      "b": null,
      "f": [],
      "hasBody": false,
      "hasHeaders": false,
      "multi": false,
      "bodyEnc": null
    }
  },
  "events": {
    "jobProgress": {
      "ws": "jobProgress",
      "hasParams": true
    },
    "systemNotice": {
      "ws": "systemNotice",
      "hasParams": false
    }
  }
};

/** Manifests for apps that talk to more than one spec, keyed by name. */
export const manifests: Record<string, Manifest> = {};

export default manifest;
