/**
 * # 11 · fullstack — manifest generator
 *
 * Writes the spec's **zod-free runtime manifest** to `app/manifest.gen.ts`, a plain data
 * module the browser app imports. Because the only thing it imports is the `Manifest`
 * *type* (erased), the Vite browser build tree-shakes zod out entirely — no special plugin.
 *
 * Run by `pnpm fullstack:gen` (and before the app build).
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { manifestFromSpec } from '@ayepi/core';
import { api } from '../shared/spec';

const out = fileURLToPath(new URL('../app/manifest.gen.ts', import.meta.url));
const manifest = manifestFromSpec(api);

const body = `// AUTO-GENERATED by scripts/gen-manifest.ts — do not edit by hand.
// The zod-free runtime manifest, imported by app/main.ts as a plain data module (so the
// Vite browser build tree-shakes zod away — no plugin required).
/* eslint-disable */
import type { Manifest } from '@ayepi/core/client';

const manifest: Manifest = ${JSON.stringify(manifest, null, 2)};

export default manifest;
`;

writeFileSync(out, body);
console.log('wrote app/manifest.gen.ts');
